# rubocop --format fuubar --format offenses -R

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Blocks:
  Enabled: false

Documentation:
  Enabled: false

Style/MethodLength:
  Enabled: false
  CountComments: false
  Max: 20

ClassLength:
  Enabled: false

CommentIndentation:
  Enabled: false

AssignmentInCondition:
  Enabled: false

GlobalVars:
  AllowedVariables: ['$rollout']
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'spec/spec_helper.rb'

LeadingCommentSpace:
  Enabled: false

# Hope to soon enable
ClassAndModuleChildren:
  Enabled: false

ClassVars:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Eval:
  Exclude:
    - 'app/models/sieble.rb'

GuardClause:
  MinBodyLength: 3

HandleExceptions:
  Enabled: false

Lambda:
  Enabled: false

ParameterLists:
  Enabled: false

SingleLineMethods:
  Enabled: false

Style/LineLength:
  Enabled: false

Rails/Validation:
  Enabled: false

Void:
  Exclude:
    - 'spec/**/*'
