# rubocop --format fuubar --format offenses -R
inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'app/graph/**/*'

  UseCache: true
  CacheRootDirectory: 'cache/'
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  CountComments: false
  Max: 20

GlobalVars:
  AllowedVariables: ['$rollout']

GuardClause:
  MinBodyLength: 3

RegexpLiteral:
  Exclude:
    - 'Guardfile'

ClassLength:
  Enabled: false

BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb\
    - Gemfile
    - Guardfile
    - lib/tasks/mpdx.rake

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
