# rubocop --format fuubar --format offenses -R
inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

  UseCache: true
  CacheRootDirectory: 'cache/'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  CountComments: false
  Max: 20

GlobalVars:
  AllowedVariables: ['$rollout']
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'spec/spec_helper.rb'

Eval:
  Exclude:
    - 'app/models/sieble.rb'

GuardClause:
  MinBodyLength: 3

RegexpLiteral:
  Exclude:
    - 'Guardfile'

Void:
  Exclude:
    - 'spec/**/*'

ClassLength:
  Enabled: false
