# rubocop --format fuubar --format offenses -R

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Blocks:
  Enabled: false

Documentation:
  Enabled: false

Style/MethodLength:
  Enabled: false
  CountComments: false
  Max: 20

ClassLength:
  Enabled: false

CommentIndentation:
  Enabled: false

AssignmentInCondition:
  Enabled: false

GlobalVars:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'spec/spec_helper.rb'

# Hope to soon enable
AccessorMethodName:
  # we have a bunch of methods starting with get_
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassVars:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Eval:
  Enabled: false

GuardClause:
  MinBodyLength: 3
  Exclude:
   - 'app/models/**/*'

HandleExceptions:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

Lambda:
  Enabled: false

ParameterLists:
  Enabled: false

SingleLineMethods:
  Enabled: false

Style/LineLength:
  Enabled: false

Style/Next:
  Enabled: false

Rails/Validation:
  Enabled: false

Void:
  Exclude:
    - 'spec/**/*'
