# rubocop --format fuubar --format offenses -R

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Blocks:
  Enabled: false

Documentation:
  Enabled: false

Style/MethodLength:
  Enabled: false
  CountComments: false
  Max: 20

CommentIndentation:
  Enabled: false

AssignmentInCondition:
  Enabled: false

# Hope to soon enable
CyclomaticComplexity:
  Enabled: false

GuardClause:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

Lambda:
  Enabled: false

Style/LineLength:
  Enabled: false

Style/Next:
  Enabled: false

Void:
  Exclude:
    - 'spec/**/*'
