# rubocop --format fuubar --format offenses -R

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Blocks:
  Enabled: false

Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  CountComments: false
  Max: 20

ClassLength:
  Enabled: false

CommentIndentation:
  Enabled: false

AssignmentInCondition:
  Enabled: false

GlobalVars:
  AllowedVariables: ['$rollout']
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'spec/spec_helper.rb'

LeadingCommentSpace:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

# Hope to soon enable
ClassVars:
  Enabled: false

CyclomaticComplexity:
  Enabled: false
PerceivedComplexity:
  Enabled: false

Eval:
  Exclude:
    - 'app/models/sieble.rb'

GuardClause:
  MinBodyLength: 3

HandleExceptions:
  Enabled: false

Lambda:
  Exclude:
    - 'spec/**/*'

SingleLineMethods:
  Enabled: false

Metrics/LineLength:
  Enabled: false

RegexpLiteral:
  Exclude:
    - 'Guardfile'

Void:
  Exclude:
    - 'spec/**/*'
