LANGUAGES_CONSTANT = {
  'en-us'      => 'US English',
  'ar'         => 'Arabic',
  'zh-hans-cn' => 'Chinese (Simplified)',
  'fr-fr'      => 'French (France)',
  'fr-ca'      => 'French (Canadian)',
  'de'         => 'German',
  'id'         => 'Indonesian',
  'it'         => 'Italian',
  'ko'         => 'Korean',
  'pl'         => 'Polish',
  'pt-BR'      => 'Portuguese (Brasil)',
  'ru'         => 'Russian',
  'es-419'     => 'Spanish (Latin America)',
  'th'         => 'Thai',
  'tr'         => 'Turkish',
  'uk'         => 'Ukranian',
  'hy'         => 'Armenian'
}.freeze
