# This is an extra mpdx_api Sidekiq worker config for memory gluttonous jobs (jobs that are known to use a lot of memory).
#
# All jobs can be processed by these workers, but the api_account_list_import_data queue is excluded:
# Those jobs flood the queue and run long which blocks other jobs from running,
# excluding them from these workers should help allow other jobs to process.
#
# The thread count (concurrency) is 1, to decrease memory usage as much as possible.
#
# Queue Weights (priority):
#   10: Jobs that are initiated by user's who are expecting them to finish soon.
#       Or other jobs that we never want blocked.
#    2: Default priority.
#    1: Jobs that should never block other jobs.
---
:verbose: false
:concurrency: 1
:queues:
  - ["api_account_list",                                 2]
  - ["api_account_list_import_data_enqueuer_worker",     10]
  - ["api_admin_account_list_reset_worker",              10]
  - ["api_admin_fix_worker",                             2]
  - ["api_contact_dup_contacts_merge_worker",            10]
  - ["api_contact_suggested_changes_updater_worker",     10]
  - ["api_csv_import_contact_worker",                    10]
  - ["api_currency_rates_fetcher_worker",                2]
  - ["api_default",                                      2]
  - ["api_google_contacts_sync_enqueuer_worker",         10]
  - ["api_google_email_sync_enqueuer_worker",            2]
  - ["api_google_sync_data_worker",                      1]
  - ["api_import",                                       10]
  - ["api_import_csv",                                   10]
  - ["api_import_google",                                10]
  - ["api_import_tnt",                                   10]
  - ["api_import_tnt_data_sync",                         10]
  - ["api_lower_retry_worker",                           2]
  - ["api_mail_chimp_sync_worker",                       1]
  - ["api_org_donor_accounts_address_cleaner",           2]
  - ["api_organization",                                 2]
  - ["api_organization_fetcher_worker",                  2]
  - ["api_person_facebook_account",                      2]
  - ["api_person_organization_account",                  2]
  - ["api_pls_account",                                  2]
  - ["api_prayer_letters_account",                       2]
  - ["api_sidekiq_cron_worker",                          2]
  - ["api_task",                                         2]
  - ["api_task_notifications_worker",                    2]
  - ["mailers",                                          10]
