# This is the default mpdx_api Sidekiq worker config.
# It should contain most queues for mpdx_api.
# Jobs that are known to be memory gluttons / memory optimized should be excluded from this config.

# The thread count (concurrency) is moderate, to support jobs that need moderate memory.
#
# Queue Weights (priority):
#   10: Jobs that are initiated by user's who are expecting them to finish soon.
#       Or other jobs that we never want blocked.
#    2: Default priority.
#    1: Jobs that should never block other jobs.
---
:verbose: false
:concurrency: 5
:queues:
  - ["api_background_batch_request",                     10]
  - ["api_mail_chimp_sync_worker",                       10]
  - ["api_account_list_import_data",                     2]
  - ["api_donation_amount_recommendation_remote_worker", 2]
  - ["api_organization_from_query_url_worker",           2]
  - ["api_organizations_from_csv_url_worker",            2]
  - ["api_person_facebook_account",                      2]
  - ["api_pls_account",                                  2]
  - ["api_prayer_letters_account",                       2]
  - ["api_sidekiq_cron_worker",                          2]
  - ["api_task",                                         2]
  - ["api_task_notifications_worker",                    2]
  - ["api_google_sync_data_worker",                      1]
  - ["default",                                          1]

