# This is the default mpdx_api Sidekiq worker config for staging.
# It should contain all queues for mpdx_api (but not Classic).
# The thread count (concurrency) is low, to support jobs that consume a lot of memory.
---
:verbose: false
:concurrency: 2
:queues:
  - ["api_account_list",                                 2]
  - ["api_account_list_import_data",                     1]
  - ["api_account_list_import_data_enqueuer_worker",     10]
  - ["api_admin_account_list_reset_worker",              10]
  - ["api_admin_fix_worker",                             2]
  - ["api_contact_dup_contacts_merge_worker",            10]
  - ["api_contact_suggested_changes_updater_worker",     10]
  - ["api_csv_import_contact_worker",                    10]
  - ["api_currency_rates_fetcher_worker",                2]
  - ["api_default",                                      2]
  - ["api_google_contacts_sync_enqueuer_worker",         10]
  - ["api_google_email_sync_enqueuer_worker",            2]
  - ["api_google_sync_data_worker",                      1]
  - ["api_import",                                       10]
  - ["api_import_csv",                                   10]
  - ["api_import_gifts_and_appeals_from_tnt_worker",     2]
  - ["api_import_google",                                10]
  - ["api_import_tnt",                                   10]
  - ["api_import_tnt_data_sync",                         10]
  - ["api_lower_retry_worker",                           2]
  - ["api_mail_chimp_sync_worker",                       1]
  - ["api_org_donor_accounts_address_cleaner",           2]
  - ["api_organization",                                 2]
  - ["api_organization_fetcher_worker",                  2]
  - ["api_person_facebook_account",                      2]
  - ["api_person_organization_account",                  2]
  - ["api_pls_account",                                  2]
  - ["api_prayer_letters_account",                       2]
  - ["api_sidekiq_cron_worker",                          2]
  - ["api_task",                                         2]
  - ["api_task_notifications_worker",                    2]
  - ["mailers",                                          10]
